name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    container:
      image: espressif/idf:v6.0.2
      env:
        IDF_PATH: /opt/esp/idf
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Extract version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG#v}"
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build firmware
        run: |
          echo "CONFIG_EXAMPLE_WIFI_SSID=\"${{ secrets.WIFI_SSID }}\"" > sdkconfig.ci
          echo "CONFIG_EXAMPLE_WIFI_PASSWORD=\"${{ secrets.WIFI_PASSWORD }}\"" >> sdkconfig.ci
          . $IDF_PATH/export.sh
          idf.py build \
            -DPROJECT_VER="${VERSION}" \
            -DSDKCONFIG_DEFAULTS="sdkconfig.ghdfu;sdkconfig.ci"

      - name: Create release and upload
        uses: softprops/action-gh-release@v3
        with:
          name: "${{ env.TAG }}"
          tag_name: "${{ env.TAG }}"
          files: |
            build/esp-gh-dfu.bin
          draft: false
          prerelease: false
